import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const errs = [], fails = [];
const ok = (n, c, x) => { if (!c) fails.push(n + (x ? ' — ' + x : '')); else console.log('ok  ' + n); };
const FILE = 'file:///tmp/claude-0/-home-user-Dan/138b4124-109c-57a3-bc88-3111022a89e3/scratchpad/cb71.test.html';
const LS = 'cutblock71.v1';
const st = (o = {}) => Object.assign({ weights: {}, days: {}, bests: {}, settings: { hideDaily: false, fiveK: 1085, fiveKManual: false }, updatedAt: Date.now() }, o);
const sq = s => s.replace(/\s+/g, ' ');
const at = async (when) => {
  const ctx = await b.newContext({ viewport: { width: 430, height: 2400 } });
  await ctx.clock.setFixedTime(new Date(when + 'T12:00:00'));
  const p = await ctx.newPage();
  p.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  const boot = async (s) => { await p.goto(FILE);
    await p.evaluate(([k, v]) => { localStorage.clear(); localStorage.setItem(k, JSON.stringify(v)); }, [LS, s]);
    await p.reload(); await p.waitForTimeout(250); await p.click('[data-t="mind"]'); };
  return { ctx, p, boot };
};

// ===== a Wednesday: a film night by default, weeknight picks =====
let { ctx, p, boot } = await at('2026-09-30');
await boot(st());
let t = sq(await p.innerText('#dayCard'));
ok('your day, in order, no alarm', /YOUR DAY/i.test(t) && /No alarm — the order matters, not the clock/.test(t) && t.indexOf('Deep study') < t.indexOf('Run or walk') && t.indexOf('Run or walk') < t.indexOf('Meditate') && t.indexOf('Gym, 18:00') < t.indexOf('Film night with your yog bowl'), t.slice(0, 500));
await p.click('#dayCard button[data-rt="1"]'); await p.waitForTimeout(100);
ok('tapping a step ticks it for today', await p.evaluate(() => JSON.stringify(S.days[today()].rt) === '[1]'));
await p.click('#dayCard button[data-rt="1"]'); await p.waitForTimeout(100);
ok('tapping again unticks it', await p.evaluate(() => !(S.days[today()] || {}).rt));
t = sq(await p.innerText('#filmCard'));
ok('Wednesday is a film night by default', /TONIGHT IS FILM NIGHT/i.test(t), t.slice(0, 200));
const pick = await p.evaluate(() => filmPick());
ok('a weeknight pick is a series or under ~2 h', pick[2] === 'series' || pick[3] <= 125, JSON.stringify(pick));
await p.click('#filmCard button[data-film="next"]'); await p.waitForTimeout(80);
const pick2 = await p.evaluate(() => FILM_UI.pick);
ok('🔄 gives another', pick2 && pick2 !== pick[0], pick2 + ' vs ' + pick[0]);
await p.click('#filmCard button[data-film="seen"]'); await p.waitForTimeout(120);
ok('✓ Seen it crosses it off, and it syncs in settings', await p.evaluate(p2 => !!S.settings.film.seen[p2] && !filmPool().some(x => x[0] === p2), pick2));
await p.click('#filmCard button[data-fg="thriller"]'); await p.waitForTimeout(80);
ok('a genre chip filters the picks', await p.evaluate(() => filmPick()[2] === 'thriller'));
await p.evaluate(() => { E('filmCard').querySelector('details').open = true; });
await p.click('#filmCard button[data-fn="3"]'); await p.waitForTimeout(120);
t = sq(await p.innerText('#filmCard'));
ok('film nights can be changed, and Wednesday off shows the next one', await p.evaluate(() => S.settings.film.nights.indexOf(3) < 0) && /next: Friday/i.test(t), t.slice(0, 200));
ok('the day card follows: no film step tonight', /Yog bowl and relax/.test(sq(await p.innerText('#dayCard'))));
t = sq(await p.innerText('#spotCard'));
ok('get out of Bassingham, with a place', /GET OUT OF BASSINGHAM/i.test(t) && /Somewhere else/.test(t));
await p.click('#spotCard button[data-sk="hills"]'); await p.waitForTimeout(80);
ok('the hills chip picks the Lincoln Edge', /Lincoln Edge around Navenby/.test(sq(await p.innerText('#spotCard'))));
await p.click('#spotCard button[data-sk=""]'); await p.waitForTimeout(80);
const s1 = await p.evaluate(() => SPOT_UI.pick);
await p.click('#spotCard button[data-spot="next"]'); await p.waitForTimeout(80);
ok('🔄 somewhere else changes it', await p.evaluate(s => SPOT_UI.pick !== s, s1));
await p.click('[data-t="today"]');
ok('the testosterone card is on Today', /TESTOSTERONE SUPPORT/i.test(await p.innerText('#tCard')));
ok('the routine, films and places live on the Mind tab, not Today', await p.evaluate(() => !!document.querySelector('#s-mind #dayCard') && !!document.querySelector('#s-mind #filmCard') && !!document.querySelector('#s-mind #spotCard') && !document.querySelector('#s-today #dayCard')));
await p.click('[data-t="mind"]');
// mood, one good thing, boosters, phone out
await p.click('#mindCard button[data-mood="4"]'); await p.waitForTimeout(100);
ok('a mood tap is saved for today', await p.evaluate(() => S.days[today()].mood === 4));
ok('and shows in the 7-day strip', (await p.innerText('#mindCard')).includes('🙂'));
await p.click('#mindCard button[data-mood="4"]'); await p.waitForTimeout(100);
ok('tapping it again clears it', await p.evaluate(() => !(S.days[today()] || {}).mood));
await p.fill('#inGood', 'parkrun with Tom'); await p.press('#inGood', 'Tab'); await p.waitForTimeout(100);
ok('one good thing is saved', await p.evaluate(() => S.days[today()].good === 'parkrun with Tom'));
await p.click('#mindCard button[data-boost="people"]'); await p.waitForTimeout(100);
ok('a booster ticks', await p.evaluate(() => S.days[today()].mb.indexOf('people') >= 0));
await p.click('#mindCard button[data-phone="1"]'); await p.waitForTimeout(100);
ok('phone out tonight sets the same toggle as the log', await p.evaluate(() => S.days[today()].phoneOut === true));
ok('it points to help if mood stays low', /Samaritans on 116 123/.test(await p.innerText('#mindCard')));
ok('no film is listed twice', await p.evaluate(() => new Set(FILMS.map(f => f[0])).size === FILMS.length));
await ctx.close();

// ===== a Saturday: rest day routine, film night =====
({ ctx, p, boot } = await at('2026-10-03'));
await boot(st());
t = sq(await p.innerText('#dayCard'));
ok('Saturday is a rest day: a walk somewhere new, refeed, film', /rest day/i.test(t) && /A walk somewhere new/.test(t) && /Refeed meals/.test(t) && /Film night with the popcorn/.test(t) && !/Gym, 18:00/.test(t), t.slice(0, 300));
const wkend = await p.evaluate(() => filmPick());
ok('a weekend night can pick a long film', !!wkend);
await ctx.close();

// ===== sets per muscle on the gym log =====
({ ctx, p, boot } = await at('2026-09-28'));
await boot(st({ days: { '2026-09-28': { gym: true, split: 'chest' } } }));
await p.click('[data-t="today"]');
const put = async (m, v) => { await p.fill(`#setsBox input[data-sets="${m}"]`, String(v)); await p.press(`#setsBox input[data-sets="${m}"]`, 'Tab'); await p.waitForTimeout(120); };
ok('a chest day asks for chest and triceps sets', await p.evaluate(() => [...document.querySelectorAll('#setsBox input[data-sets]')].map(i => i.dataset.sets).join() === 'Chest,Triceps'));
await put('Chest', 8); await put('Triceps', 3);
let sb = sq(await p.innerText('#setsBox'));
ok('8 chest sets on a cut: just right', /CHEST · JUST RIGHT/i.test(sb) && /inside 6–10/.test(sb), sb);
ok('3 triceps: light, with a nudge not a telling-off', /TRICEPS · LIGHT/i.test(sb) && /1–2 more hard sets/.test(sb));
await put('Chest', 11);
ok('11 chest: on the high side — recovery and running pay', /CHEST · ON THE HIGH SIDE/i.test(sq(await p.innerText('#setsBox'))) && /your running pays/.test(sq(await p.innerText('#setsBox'))));
await put('Chest', 14);
ok('14 in one session: too much for one session', /CHEST · TOO MUCH FOR ONE SESSION/i.test(sq(await p.innerText('#setsBox'))));
ok('sets are saved on the day', await p.evaluate(() => S.days['2026-09-28'].sets.Chest === 14 && S.days['2026-09-28'].sets.Triceps === 3));
// a second session in the same week adds up
await boot(st({ days: { '2026-09-28': { gym: true, split: 'chest', sets: { Chest: 6 } }, '2026-09-26': { gym: true, split: 'chest', sets: { Chest: 6 } } } }));
ok('the week sums Mon–Sun only (last Saturday is last week)', await p.evaluate(() => weekSets('2026-09-28').Chest === 6));
await boot(st({ days: { '2026-09-28': { gym: true, split: 'chest', sets: { Chest: 6 } }, '2026-10-01': { gym: true, split: 'other', sets: { Chest: 6 } } } }));
ok('a second go in the same week adds up', await p.evaluate(() => weekSets('2026-10-01').Chest === 12));
await p.click('[data-t="training"]');
const tt = sq(await p.innerText('#s-training'));
ok('the Training tab shows this week’s sets with a verdict', /THIS WEEK/i.test(tt) && /Chest 6–10 12–18 12 on the high side/i.test(tt), (tt.match(/Chest 6.{0,80}/) || [''])[0]);
ok('calisthenics days do not ask for sets', await p.evaluate(() => setsBoxHTML('2026-09-28') !== '' && (S.days['2026-09-29'] = { gym: true, split: 'calis' }, setsBoxHTML('2026-09-29') === '')));
await ctx.close();

await b.close();
if (errs.length) fails.push(...errs);
console.log(fails.length ? 'FAIL (' + fails.length + ')\n - ' + fails.join('\n - ') : 'all passed');
