import type { ContentItem } from '../schema';

export const hormonesSymptomsContent: ContentItem[] = [
  {
    id: 'hormones-frequent-urination',
    category: 'hormones-symptoms',
    trimester: [1, 2, 3],
    title: 'Why you need the loo more often',
    tip: "Your kidneys are working harder in pregnancy, and your growing baby presses on your bladder — that's why you'll likely need to wee more, especially later on.",
    body: 'Your kidneys are working harder in pregnancy — blood flow through them increases by about 50%, and hormonal changes cause your body to hold onto more fluid. Combined with your growing baby pressing on your bladder, this is why you\'ll likely need to wee more often, especially as pregnancy progresses.',
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'urination'],
  },
  {
    id: 'hormones-heartburn-constipation',
    category: 'hormones-symptoms',
    trimester: [1, 2, 3],
    title: 'Why heartburn and constipation are so common',
    tip: 'The hormone progesterone relaxes smooth muscle throughout your body — including your digestive tract — which is why heartburn and constipation are so common.',
    body: "The hormone progesterone relaxes smooth muscle throughout your body — including the valve between your stomach and food pipe, and your digestive tract. That's why heartburn and constipation are so common, especially as pregnancy progresses.",
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'heartburn', 'constipation'],
  },
  {
    id: 'hormones-nausea',
    category: 'hormones-symptoms',
    trimester: [1],
    title: "Why \"morning sickness\" happens",
    tip: 'Rising pregnancy hormones affect your digestive system directly — around 8 in 10 pregnant people experience some degree of nausea in the first trimester.',
    body: 'Rising hormones — particularly the ones that support the pregnancy in early weeks — affect your digestive system directly, which is a major reason nausea is so common in the first trimester. Around 8 in 10 pregnant people experience some degree of it. It usually eases as the trimester goes on, though not always on a fixed schedule.',
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'nausea', 'morning sickness'],
  },
  {
    id: 'hormones-breathlessness',
    category: 'hormones-symptoms',
    trimester: [1, 3],
    title: 'Why you might feel breathless',
    tip: 'Progesterone changes your breathing from early pregnancy, and later your growing baby takes up space your lungs would normally use.',
    body: 'Progesterone affects your breathing control centre, meaning you naturally breathe in more air with each breath from early pregnancy. Later on, your growing baby also takes up space your lungs would normally use, which is part of why breathlessness is common in the third trimester.',
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'breathlessness'],
  },
  {
    id: 'hormones-swelling',
    category: 'hormones-symptoms',
    trimester: [2, 3],
    title: 'Swelling — what\'s normal, and when to get help',
    tip: 'Mild swelling in your ankles, hands, or face is normal. Sudden or extreme swelling with a rapid rise in blood pressure needs urgent medical attention.',
    body: "Increased blood volume and fluid retention are a normal part of pregnancy and can cause mild swelling in your ankles, hands, or face. However, sudden or extreme swelling — especially combined with a rapid rise in blood pressure — can be a sign of pre-eclampsia and needs urgent medical attention. If this happens, contact your midwife, GP, or maternity unit straight away rather than waiting to see if it settles.",
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'swelling', 'pre-eclampsia'],
    isRedFlag: true,
  },
  {
    id: 'hormones-fatigue',
    category: 'hormones-symptoms',
    trimester: [1, 3],
    title: 'Why pregnancy is so tiring',
    tip: 'Your heart is pumping up to 30–50% more blood by the third trimester — tiredness, especially early and late on, is a normal reflection of that.',
    body: "Your body is working significantly harder — your heart is pumping up to 30-50% more blood by the third trimester, and your metabolism has shifted to support your growing baby. Tiredness, especially in the first and third trimesters, is a normal reflection of that, not a sign anything's wrong.",
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'fatigue', 'tiredness'],
  },
  {
    id: 'hormones-mood-swings',
    category: 'hormones-symptoms',
    trimester: [1, 2, 3],
    title: 'Mood swings have a real physical driver',
    tip: 'Rapidly shifting hormone levels genuinely affect mood — this is a real physical driver, not just "thinking too much about it."',
    body: "Rapidly rising and shifting hormone levels — particularly oestrogen and progesterone — genuinely affect mood, alongside all the normal life adjustment that comes with pregnancy. This is a real physical driver, not just \"thinking too much about it,\" and it's completely normal to notice your emotions feeling less predictable than usual.",
    sourceIds: ['nct-hormones-pregnancy-labour', 'jee-sawal-2024-cureus'],
    tags: ['symptoms', 'hormones', 'mood'],
  },
];
