import type { ContentItem } from '../schema';

export const stressMentalHealthContent: ContentItem[] = [
  {
    id: 'stress-normalising',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: "You're not alone in feeling worried sometimes",
    tip: "It's completely normal to have some worries during pregnancy. Most pregnant women experience only mild to moderate stress, not high stress.",
    body: 'In a study of over 1,500 pregnant women, only 6% were classified as having high stress, 78% reported low-to-moderate stress, and 16% reported no stress at all. Whatever you\'re feeling, you\'re not alone, and some worry is a normal part of the transition into pregnancy and parenthood.',
    sourceIds: ['alves-2021-resilience-stress'],
    tags: ['stress', 'mental health', 'reassurance'],
  },
  {
    id: 'stress-relaxation-techniques',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: 'Relaxation techniques are safe, and the evidence is real',
    tip: 'Slow breathing, calming music, gentle stretching, or a few minutes of mindfulness are safe throughout pregnancy and can genuinely help.',
    body: 'A systematic review and meta-analysis of 32 trials and almost 4,000 women found relaxation interventions — music, breathing, progressive muscle relaxation, yoga, mindfulness, hypnosis — significantly reduced maternal stress, anxiety, and depressive symptoms on validated scales, and were also associated with a modest increase in birth weight. Simple relaxation techniques are safe throughout pregnancy, and clinical studies show they can genuinely help with stress, anxiety, and low mood.',
    sourceIds: ['abera-2024-relaxation-meta-analysis'],
    tags: ['stress', 'relaxation', 'mental health'],
  },
  {
    id: 'stress-mindfulness',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: 'Mindfulness — worth trying, no real downside',
    tip: 'Mindfulness is one of the most well-studied relaxation techniques for pregnancy — even a few minutes a day may help, and there\'s no real downside to trying it.',
    body: 'A review of the evidence found sufficient support for mindfulness practice in pregnancy to help reduce anxiety, depression, and stress, with benefits that may continue into the postpartum period. Because these techniques carry very low risk, the review concluded that all pregnant women should be encouraged to try them — even a few minutes a day.',
    sourceIds: ['babbar-2021-mindfulness-review'],
    tags: ['mindfulness', 'stress', 'mental health'],
  },
  {
    id: 'stress-coping-strategies',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: 'More than one way to cope with a hard day',
    tip: 'Talking to someone you trust, writing down how you feel, or putting on music you love can genuinely help.',
    body: 'Talking to someone — a partner, friend, family member, or professional — helps by making you notice and label your feelings, reducing the sense of uncertainty. Writing down feelings freely, with no concern about being read, can help on its own or alongside other support. Music and singing can calm emotions, enhance wellbeing, and promote bonding with your baby. There\'s more than one way to cope with a hard day.',
    sourceIds: ['nct-common-emotions'],
    tags: ['coping', 'stress', 'mental health'],
  },
  {
    id: 'stress-reach-out',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: "It's OK to tell your midwife how you're feeling",
    tip: "If your worries feel like more than you can manage, tell your midwife or GP. It's normal to ask for help, and you won't be judged.",
    body: "It's fine, and important, to share worries with your midwife or GP — they can offer reassurance or point you toward the right support without judgment. Many people worry about revealing mental health struggles for fear of stigma or judgement. In reality, health and social care professionals do their best to keep families together, and answering honestly helps you get the support that's actually right for you.",
    sourceIds: ['nhs-mental-health-pregnancy', 'nct-common-emotions'],
    tags: ['mental health', 'support', 'midwife'],
  },
  {
    id: 'stress-signposting',
    category: 'stress-mental-health',
    trimester: [1, 2, 3],
    title: 'Where to find more support',
    tip: "Tommy's, PANDAS, and your local Family Hub are established UK-specific places for more support.",
    body: "If you'd like more support, a few established UK-specific resources: Tommy's has a wellbeing plan and information on emotional changes in pregnancy; PANDAS supports parents affected by perinatal mental illness; and your local council may run a Family Hub.",
    sourceIds: ['nhs-support-signposting'],
    tags: ['support', 'signposting', 'mental health'],
  },
];
