import type { ContentItem } from '../schema';

export const weightBodyImageContent: ContentItem[] = [
  {
    id: 'weight-no-target-number',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: "There's no single 'correct' amount of weight to gain",
    tip: "Weight gain varies a lot between individuals. Current UK guidance deliberately doesn't set one fixed number to aim for.",
    body: 'The UK government evidence review (SACN) states plainly that there are currently no UK evidence-based guidelines on a recommended weight-gain range in pregnancy, because the evidence doesn\'t support one precise target working for everyone. The NHS separately confirms that gain varies widely between individuals and comes from a mix of the baby, placenta, fluid, blood volume, and fat stores for breastfeeding — not something to track against a fixed figure. If you\'re finding yourself worrying about a number, that\'s genuinely not something you need to carry.',
    sourceIds: ['sacn-2026-maternal-weight', 'nhs-weight-gain-pregnancy'],
    tags: ['weight', 'body image', 'reassurance'],
  },
  {
    id: 'weight-both-directions-risk',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: "It's not just about avoiding gaining 'too much'",
    tip: "Gaining less than your body needs carries its own risks too, and it's more common than people realise.",
    body: "A 2025 systematic review of 1.6 million women found real outcomes attached to both directions: gaining on the lower end was linked to higher risk of preterm birth, small-for-gestational-age babies, and low birth weight; gaining on the higher end was linked to higher risk of caesarean birth, high blood pressure disorders, and NICU admission. A separate 2025 study across six countries, including the UK, found more than half of women didn't gain 'enough' by current standards, and this was linked to double the risk of low birthweight and gestational diabetes. This isn't a reason to worry about a number, just a reason not to intentionally restrict.",
    sourceIds: ['teede-2025-bmj-gestational-weight-gain', 'jabin-2025-interbio-weight-gain'],
    tags: ['weight', 'body image'],
  },
  {
    id: 'weight-underweight-consideration',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: 'Being underweight is worth a conversation too',
    tip: "If you're underweight, it's worth mentioning to your midwife or GP — being underweight has its own considerations for how your baby grows.",
    body: 'A US cohort study of over 16,000 women found underweight mothers (BMI under 18.5) had notably higher rates of small-for-gestational-age babies (23% vs 13.5%) and low birth weight (15% vs 9%) compared with normal-weight mothers, even after adjusting for other factors. This isn\'t something to self-manage with a target number, just something worth a conversation with your midwife or GP.',
    sourceIds: ['chahal-2024-underweight-outcomes'],
    tags: ['weight', 'underweight'],
  },
  {
    id: 'weight-cravings-eating-for-two',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: 'Cravings are normal — no guilt required',
    tip: "Food cravings are extremely common and nothing to feel guilty about. The odd craving isn't something to fight.",
    body: "A qualitative study of 68 pregnant women found cravings were commonly used to justify eating foods women wouldn't normally allow themselves, often invoking \"eating for two\" — even though most participants also knew this wasn't literally true. Cravings were closely tied to emotional states: guilt commonly followed indulging, but distress also followed resisting cravings. Acceptance-based approaches — allowing a craving in moderation rather than fighting it — were associated with less psychological distress than strict restriction. You don't need extra calories until the third trimester, but a bit of flexibility tends to feel better than a fight.",
    sourceIds: ['blau-food-cravings-qualitative'],
    tags: ['cravings', 'body image', 'weight'],
  },
  {
    id: 'weight-body-image-trajectory',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: 'Body image often improves during pregnancy',
    tip: 'Many women feel more at ease with their bodies during pregnancy than before it — body image concerns tend to be more common after birth.',
    body: "A German longitudinal study following 136 women found body image dissatisfaction was actually lower during pregnancy (2.9–6.6% of women reporting elevated dissatisfaction) than commonly assumed — decreasing from pre-pregnancy levels — but rose to around 10–11% at three and six months postpartum. Attention often shifts from appearance to function during pregnancy. Body image concerns tend to be more common in the months after birth, so that's a good time to be gentle with yourself and ask for support if you need it.",
    sourceIds: ['linde-body-image-trajectory'],
    tags: ['body image', 'postpartum'],
  },
  {
    id: 'weight-support-gap',
    category: 'weight-body-image',
    trimester: [1, 2, 3],
    title: "You're not alone if nobody's talked to you about this",
    tip: "If it feels like nobody's discussed weight or body image with you, you're not alone — many women report exactly that.",
    body: 'A 2025 Swiss qualitative study of pregnant women, midwives, and dietitians found most women reported little to no discussion of weight or body image with their gynaecologist — often weighed without comment, leaving them to search for information themselves or worry silently. Midwives and dietitians, when involved, took a markedly more supportive, non-judgmental approach. It doesn\'t mean it\'s not worth raising — midwives, in particular, tend to be a supportive place to start that conversation if you want one.',
    sourceIds: ['carrard-2025-weight-body-image-qualitative'],
    tags: ['support', 'body image', 'weight'],
  },
];
