import type { Symptom } from './schema';

/**
 * Every entry follows the same shape deliberately: why it's happening
 * (reassurance — there's a real physical reason), what actually helps, and
 * the point at which it stops being routine. The `flag` field is never
 * empty; where a symptom is genuinely harmless that's stated outright
 * rather than left ambiguous.
 */
export const symptoms: Symptom[] = [
  {
    id: 'wee',
    icon: '🚽',
    name: 'Needing the loo',
    why: 'Your kidneys are working significantly harder — blood flow through them rises by about 50% — and hormones make your body hold onto more fluid. Later on, your baby presses on your bladder too.',
    help: 'Cut drinks late in the evening but stay well hydrated in the day. Rocking gently forwards and back on the toilet can help empty your bladder properly.',
    flag: 'Pain or blood when peeing needs same-day GP contact — possible UTI.',
    sourceIds: ['nhs-common-problems', 'jee-sawal-2024'],
  },
  {
    id: 'heartburn',
    icon: '🔥',
    name: 'Heartburn',
    why: 'Progesterone relaxes smooth muscle everywhere — including the valve between your stomach and food pipe. Your growing baby pressing upward adds to it.',
    help: 'Smaller, more frequent meals. Nothing within 3 hours of bed. Sit upright after eating. Cut back on caffeine, spicy and fatty food. Sleeping propped up on your left side helps.',
    flag: "Antacids are generally fine — but not within 2 hours of iron or folic acid, as they block absorption. Heartburn that antacids won't touch, alongside headache or swelling, needs checking.",
    sourceIds: ['nhs-common-problems', 'nct-hormones'],
  },
  {
    id: 'nausea',
    icon: '🤢',
    name: 'Nausea & sickness',
    why: 'Rising hormones in early pregnancy affect your digestive system directly. Around 8 in 10 pregnant people get some degree of it, usually easing by weeks 16–20.',
    help: 'Rest (tiredness makes it worse). Dry toast or a plain biscuit before getting up. Small frequent meals, high carb, low fat. Cold food if smells set you off. Ginger has some evidence behind it. Acupressure bands may help.',
    flag: "Can't keep fluids down for 24 hours, dark or no urine for 8+ hours, weight loss, or vomiting blood — contact your midwife or 111. This can be hyperemesis and needs treatment.",
    sourceIds: ['nhs-morning-sickness', 'nct-hormones'],
  },
  {
    id: 'tired',
    icon: '😴',
    name: 'Tiredness',
    why: 'Your heart is pumping up to 30–50% more blood by the third trimester and your whole metabolism has shifted. First and third trimesters hit hardest.',
    help: "Rest where you can, feet up. Accept help. Being tired won't harm you or your baby. Strange dreams about the baby or labour are completely normal too.",
    flag: 'Sleeplessness alongside hopelessness or losing interest in things you enjoyed can be a sign of depression — worth mentioning to your midwife.',
    sourceIds: ['nhs-common-problems', 'jee-sawal-2024'],
  },
  {
    id: 'back',
    icon: '🦴',
    name: 'Back pain',
    why: 'Ligaments soften and stretch to prepare for labour, which puts strain on your lower back and pelvis. Your shifting centre of gravity adds to it.',
    help: 'Bend your knees when lifting. Avoid heavy lifting. Flat shoes. Balance shopping between two bags. Well-supported sitting. A warm bath or massage. Paracetamol is fine unless told otherwise.',
    flag: 'With fever, bleeding, or pain when peeing — contact your GP urgently. Losing feeling in your legs, bottom or genitals — call 999.',
    sourceIds: ['nhs-common-problems'],
  },
  {
    id: 'pelvic',
    icon: '🩹',
    name: 'Pelvic pain (PGP)',
    why: 'Pelvic joints stiffening or moving unevenly. Affects up to 1 in 5 pregnancies. Not harmful to your baby, but genuinely painful.',
    help: 'Ask about a physio referral — earlier is better. Keep active but avoid what hurts. Sit down to dress. Pillow between your legs in bed. Keep knees together getting in and out of the car. A support belt may help.',
    flag: 'Most women with PGP still have a vaginal birth. Put it in your birth plan so staff know.',
    sourceIds: ['nhs-common-problems'],
  },
  {
    id: 'swelling',
    icon: '🦶',
    name: 'Swelling',
    why: 'Your body holds more water in pregnancy, and it gathers in the lowest parts — worse by evening, in hot weather, or after standing.',
    help: 'Feet up when you can. Avoid long standing. Comfortable shoes and socks with no tight straps. Foot exercises: bend and stretch 30 times, rotate 8 each way.',
    flag: 'SUDDEN swelling of face, hands or feet — especially with headache, vision changes, or pain under your ribs — needs checking immediately. This can be pre-eclampsia.',
    sourceIds: ['nhs-common-problems', 'nhs-get-help'],
  },
  {
    id: 'breathless',
    icon: '💨',
    name: 'Breathlessness',
    why: 'Progesterone affects your breathing control centre, so you take in more air per breath from early on. Later, your baby takes up space your lungs would use.',
    help: 'Slow down, sit upright, and give yourself permission to do less. Common and expected, particularly in the third trimester.',
    flag: 'Sudden breathlessness, breathlessness lying flat, or with chest pain or dizziness — get checked immediately.',
    sourceIds: ['nhs-common-problems', 'nhs-dvt'],
  },
  {
    id: 'mood',
    icon: '🌊',
    name: 'Mood swings',
    why: 'Rapidly shifting oestrogen and progesterone genuinely affect mood — alongside all the normal life adjustment of pregnancy. This is a real physical driver, not "overthinking".',
    help: 'Talk to someone. Write it down. Music. A few minutes of slow breathing. All evidence-backed, all free.',
    flag: 'If low mood or anxiety is affecting your daily life, tell your midwife or GP. Up to 1 in 4 people experience anxiety symptoms in pregnancy.',
    sourceIds: ['nct-emotions', 'nct-hormones'],
  },
  {
    id: 'cramp',
    icon: '🦵',
    name: 'Leg cramp',
    why: 'Common, especially at night, in the calf or foot. Circulation changes are part of it.',
    help: 'Gentle regular exercise, especially ankle and leg movement. During a cramp, pull your toes hard up toward your ankle or rub the muscle firmly.',
    flag: 'Pain, swelling and tenderness in ONE leg, worse when walking, is different from cramp — that needs urgent checking for a clot.',
    sourceIds: ['nhs-common-problems', 'nhs-dvt'],
  },
  {
    id: 'constipation',
    icon: '🌾',
    name: 'Constipation',
    why: 'Hormonal changes slow your digestive tract, often very early in pregnancy. Iron supplements can make it worse.',
    help: 'High-fibre foods — wholemeal bread, cereals, fruit, veg, beans and lentils. Plenty of water. Regular exercise.',
    flag: "If an iron supplement is the cause, ask your GP about managing without it or switching type — don't just stop.",
    sourceIds: ['nhs-common-problems'],
  },
  {
    id: 'piles',
    icon: '🪑',
    name: 'Piles',
    why: 'Swollen blood vessels around your bottom, often caused by constipation and straining. Common, and not just in pregnancy.',
    help: "Treat the constipation first — fibre and water. Don't strain. Avoid long standing or sitting. A cloth wrung out in iced water can ease it. Pat rather than rub after the loo.",
    flag: "Ask your midwife or pharmacist before using any cream — don't self-select one.",
    sourceIds: ['nhs-common-problems'],
  },
  {
    id: 'skin',
    icon: '✨',
    name: 'Skin changes',
    why: 'Hormones darken nipples, moles, freckles, and often create a dark line down your belly. Your skin may darken in patches or all over.',
    help: "These fade after birth (nipples may stay slightly darker). You'll burn more easily in the sun — high-factor sunscreen and don't stay out long.",
    flag: 'Itchy skin, especially palms and soles and worse at night, is different — that needs checking for a liver condition (ICP).',
    sourceIds: ['nhs-common-problems', 'nhs-get-help'],
  },
  {
    id: 'stretch-marks',
    icon: '〰️',
    name: 'Stretch marks',
    why: 'The middle layer of skin stretches and breaks in places. Affects around 8 in 10 pregnant women. Whether you get them depends largely on skin type.',
    help: 'Honestly: nothing reliably prevents them, and no cream is proven to remove them. They fade to paler marks after birth. Not something you need to fix.',
    flag: 'None — these are entirely harmless.',
    sourceIds: ['nhs-common-problems'],
  },
  {
    id: 'varicose',
    icon: '🩸',
    name: 'Varicose veins',
    why: 'Swollen veins, usually in the legs but sometimes the vulva. Uncomfortable but not harmful, and usually better after birth.',
    help: "Avoid long standing. Don't sit with legs crossed. Legs up when you can. Compression stockings from a pharmacy. Sleep with legs raised on pillows. Walking and swimming help circulation.",
    flag: 'None on their own — but new pain or swelling in one leg is a different thing and needs checking.',
    sourceIds: ['nhs-common-problems', 'nhs-dvt'],
  },
  {
    id: 'discharge',
    icon: '💧',
    name: 'Discharge',
    why: 'More discharge is normal and protective — it helps stop infection travelling up to your womb. It increases further toward the end.',
    help: 'Healthy discharge is thin, clear or milky, without a strong smell. Loose cotton underwear, avoid perfumed products. A pink jelly-like "show" near the end can mean labour is starting.',
    flag: 'Unpleasant smell, green or yellow colour, itching, soreness, or pain when peeing — call your midwife. Any bleeding — contact them immediately.',
    sourceIds: ['nhs-common-problems', 'nhs-get-help'],
  },
];

export const symptomById = new Map(symptoms.map((s) => [s.id, s]));
