import type { Guide } from '../schema';

export const birthGuides: Guide[] = [
  {
    id: 'where-to-give-birth',
    section: 'birth-place',
    title: 'Where to give birth',
    summary: 'Hospital, midwife-led birth centre, or home — what each actually offers.',
    body: [
      '**Hospital:** full access to obstetricians, anaesthetists, and a special care baby unit if needed. The right choice if you have medical conditions, previous pregnancy or birth complications, or are expecting more than one baby.',
      '**Birth centre (midwife-led unit):** more homely, focused on birth without medical intervention. Units attached to a hospital can transfer easily if needed; standalone units can’t offer an epidural.',
      '**Home birth:** about 1 in 50 births in England. A midwife supports you throughout; if labour isn’t progressing well, you’ll be transferred to hospital.',
    ],
    sourceIds: ['nhs-where-to-give-birth'],
  },
  {
    id: 'labour-signs',
    section: 'labour',
    title: 'Signs labour has started',
    summary: 'Contractions, a show, back pain, waters breaking — and what each feels like.',
    body: [
      '**Contractions:** your womb tightens then relaxes — like extreme period pain. They get longer, stronger and more frequent as labour progresses.',
      '**The "show":** a plug of mucus (yellow or bloody) from your cervix. Labour may follow quickly or take days — sometimes there’s no show at all.',
      '**Back pain:** from your baby’s head against your spine.',
      '**Needing the toilet more, or losing control of it:** very common, and nothing to be embarrassed about.',
      '**Waters breaking:** usually a small pop and trickle, not a dramatic gush. It should be clear — contact your midwife immediately if it’s smelly or coloured.',
    ],
    sourceIds: ['nhs-labour-signs'],
  },
  {
    id: 'when-to-call-labour',
    section: 'labour',
    title: 'When to call — don’t wait it out',
    summary: 'Every 5 minutes, waters breaking, bleeding, reduced movements, or under 37 weeks.',
    body: [
      'Call your midwife or maternity unit if you think you’re in labour, contractions are coming every 5 minutes or more, or you’re unsure about anything.',
      '**Call urgently — day or night, don’t wait:** your waters break · vaginal bleeding · baby moving less than usual · you’re under 37 weeks and think you’re in labour · any contraction lasts over 2 minutes · 6 or more contractions in 10 minutes.',
      '**Call 999** if you have a strong urge to push and think your baby is coming now.',
      'Can’t reach your midwife or unit? Call **111**.',
    ],
    sourceIds: ['nhs-labour-signs'],
    emphasis: 'warn',
  },
  {
    id: 'early-labour-tips',
    section: 'labour',
    title: 'Getting through early labour',
    summary: 'Rest, move, warm water, breathing, snacks.',
    body: [
      'Rest when you can. Gentle walking if you feel like moving. A warm bath or shower eases contraction pain. Practise your breathing — in through the nose, out through the mouth. Keep your energy up with snacks.',
      'Listen to your body over any rulebook.',
    ],
    sourceIds: ['nhs-labour-signs'],
  },
  {
    id: 'pain-relief-options',
    section: 'pain-relief',
    title: 'Pain relief options',
    summary: 'TENS, gas and air, epidural, pethidine — what each does and its trade-offs.',
    body: [
      '**TENS machine:** small electrical pulses through pads on your back, thought to boost natural endorphins. Drug-free and you stay in control — most useful in early labour rather than later stages.',
      '**Gas and air (Entonox):** breathed through a mask, works in 15–20 seconds. Won’t remove pain completely and may make you lightheaded or sick, but no harm to you or your baby, and it wears off fast.',
      '**Epidural:** local anaesthetic numbing the pain nerves, given by an anaesthetist (so not available everywhere). Works well for a difficult labour and unlikely to cause sickness — but can slow labour, and around 1 in 8 women still need additional pain relief.',
      '**Pethidine:** injection into thigh or bottom, takes around 20 minutes, helps you relax for 2–4 hours. Not suitable late in labour — it can affect your baby’s breathing and feeding. Can make you woozy, sick or forgetful.',
      'You can discuss preferences with your midwife and write them in your birth plan — and you can change your mind on the day.',
    ],
    sourceIds: ['nhs-pain-relief'],
  },
  {
    id: 'pain-relief-non-drug',
    section: 'pain-relief',
    title: 'Water birth and self-help',
    summary: 'Movement, position, breathing, and warm water.',
    body: [
      '**Self-help:** breathing, relaxation, moving around, and changing position (kneeling, squatting) all genuinely help. Knowing what to expect through antenatal classes helps some people feel more in control.',
      '**Water birth:** warm water (never above 37.5°C) aids relaxation and movement. Don’t get in too early — it can slow labour. You’ll need to leave the pool if complications arise.',
      '**Complementary methods** (acupuncture, aromatherapy, homeopathy): no strong evidence they work — mention it to your midwife if you’d like a therapist present.',
    ],
    sourceIds: ['nhs-pain-relief'],
  },
  {
    id: 'delivery-types',
    section: 'birth-place',
    title: 'Types of delivery',
    summary: 'Vaginal, VBAC, caesarean and assisted — with the actual UK proportions.',
    body: [
      '**Vaginal birth:** around 6 in 10 births in England. May start spontaneously or be induced.',
      '**Vaginal birth after caesarean (VBAC):** if there’s no medical reason against it, your chances of success are good — worth discussing pros and cons with your midwife.',
      '**Caesarean section:** nearly 3 in 10 births. Planned or emergency. Takes 40–50 minutes, with a few days’ hospital recovery. A major operation, only done when it’s the safest option.',
      '**Assisted delivery (ventouse or forceps):** just over 1 in 10 births. Local anaesthetic if you don’t already have an epidural. May need an episiotomy — a cut to widen the vaginal opening, repaired with stitches.',
    ],
    sourceIds: ['nhs-giving-birth'],
  },
  {
    id: 'antenatal-classes',
    section: 'birth-prep',
    title: 'Antenatal classes & hypnobirthing',
    summary: 'What classes cover, and what hypnobirthing does and doesn’t do.',
    body: [
      '**Antenatal classes** usually start 8–10 weeks before your due date, weekly, around 2 hours. They cover diet, exercise, labour, relaxation, delivery methods, newborn care and emotional wellbeing. NHS classes are free — ask your midwife. NCT offers paid courses including refreshers.',
      '**Hypnobirthing** uses breathing, relaxation, visualisation and self-hypnosis to reframe birth as manageable rather than frightening. The evidence-backed benefits are real: greater confidence and sense of control, reduced fear and anxiety, reported lower pain intensity and less pain relief used, and shorter labours in some studies.',
      'What it *doesn’t* do: it has no effect on epidural use or on vaginal versus caesarean rates, and it doesn’t guarantee an intervention-free birth. It is linked to a more positive birth experience regardless of how birth actually goes, with no safety downsides.',
      'One honest caveat: because breathing techniques can help you cope so well, medical staff sometimes underestimate how far labour has progressed — worth telling your midwife you’re using it.',
    ],
    sourceIds: ['nhs-antenatal-classes', 'nct-hypnobirthing'],
  },
  {
    id: 'birthing-ball',
    section: 'birth-prep',
    title: 'Using a birthing ball',
    summary: 'Sizing, positions, and the one safety check.',
    body: [
      '**Sizing:** up to 5\'8" → 65cm ball; taller → 75cm. Your knees should sit about 4 inches below your hips when seated. Check it’s **anti-burst** material — that deflates slowly if punctured rather than popping.',
      '**Sitting:** feet shoulder-width apart, barefoot or in non-slip socks; rock side to side or in circles. A good position for a birth partner to massage your back.',
      '**Leaning or hugging:** kneel and lean over or hug the ball, rocking gently.',
      '**Standing:** ball on a raised surface, lean over it from standing.',
      'Only use it in labour if you’ve practised beforehand and feel confident with it.',
    ],
    sourceIds: ['nhs-birthing-ball'],
  },
  {
    id: 'hospital-bag',
    section: 'birth-prep',
    title: 'Hospital bag checklist',
    summary: 'Pack from around 3 weeks before your due date.',
    body: [
      'Pack from around 3 weeks before your due date — only 1 in 20 babies arrive exactly on time.',
      '**For you:** birth plan and notes · comfortable labour clothes · dressing gown and slippers · nightwear (front-opening if breastfeeding) · 3 changes of clothes · knickers (disposable are useful) · nursing bras and breast pads · 2 packs super-absorbent maternity pads · wash bag · towels and your own pillow · snacks, drinks, water bottle · fan or water spray · any medicines · TENS machine and spare batteries if using · phone charger with a long cable or power bank · spare glasses or contacts.',
      '**For baby:** bodysuits, vests, sleepsuits · going-home outfit · hat, scratch mittens, socks · nappies and cotton wool or wipes · muslin squares · car seat · blanket.',
      '**For your birth partner:** change of clothes · toiletries · phone charger · snacks · swimwear if using a pool · change for parking.',
    ],
    sourceIds: ['nhs-hospital-bag'],
  },
  {
    id: 'birth-plan',
    section: 'birth-prep',
    title: 'Your birth plan',
    summary: 'What to decide in advance — and staying flexible.',
    body: [
      'A birth plan tells your team what you want — but stay flexible, as plans often change on the day, and your midwife will help you make the safest call in the moment.',
      'Worth deciding in advance: where to give birth · who’s with you (including for an assisted delivery or caesarean) · equipment or facilities you want (mats, pool) · staying active and preferred positions · immediate skin-to-skin before cord cutting · whether you’re comfortable with students or trainees present · pain relief preferences · feeding plan · consent for vitamin K if needed.',
    ],
    sourceIds: ['nhs-birth-plan'],
  },
  {
    id: 'overdue',
    section: 'birth-prep',
    title: 'If you go past your due date',
    summary: 'Normal, common — and nothing at home reliably brings labour on.',
    body: [
      'Pregnancy normally runs 37–42 weeks; your due date is just an estimate of 40 weeks. Going before or after it is common.',
      'There are **no proven ways to safely bring on labour at home**, despite what you’ll find online — raspberry leaf tea, spicy food, acupuncture. If you want to try to move things along, check with your midwife first.',
    ],
    sourceIds: ['nhs-overdue'],
  },
  {
    id: 'birth-partner',
    section: 'birth-prep',
    title: 'For your birth partner',
    summary: 'Practical things that actually help on the day.',
    body: [
      'Know the birth plan — and that it may change. Do the antenatal classes. Plan the route and parking in advance. Keep your phone charged and your own bag packed.',
      'Offer steady reassurance, but don’t take it personally if you’re asked to stop talking mid-contraction. Help with breathing focus, physical support (something to lean on), drinks and snacks. Speak up for your partner’s wishes if needed.',
      'And look after yourself too — snacks, drinks, and a short break when you can.',
    ],
    sourceIds: ['nhs-birth-partner'],
  },
];
