import type { Guide } from '../schema';

export const feedingGuides: Guide[] = [
  {
    id: 'feeding-nobody-figured-out',
    section: 'feeding-basics',
    title: 'Nobody has it figured out from day one',
    summary: '73% of mothers who breastfed hit a difficulty. You’d be in the majority, not failing.',
    body: [
      'Breastfeeding difficulties are the norm, not the exception. In a 2024 national survey, **73% of mothers who breastfed experienced a difficulty** — most commonly engorgement (42%), baby not latching well (25%), or feeling they didn’t have enough milk (25%).',
      'If you’re struggling, you are in the majority, not failing at something everyone else finds easy.',
    ],
    sourceIds: ['ohid-infant-feeding-2024'],
    emphasis: 'calm',
  },
  {
    id: 'feeding-what-helps',
    section: 'feeding-basics',
    title: 'What actually helps — from mothers who’ve been there',
    summary: 'Latch support is the single most commonly cited fix. Ask early and repeatedly.',
    body: [
      'Among mothers who wanted to breastfeed for longer, the things that would have helped most were: their **baby latching more easily (53%)**, more support from hospital staff (30%), and it being less painful (28%). Support from a community midwife or health visitor also made a real difference for many.',
      'The takeaway: ask for latch support early and repeatedly. It’s the single most commonly cited fix, and it’s exactly what midwives, health visitors and infant feeding support groups are there for.',
    ],
    sourceIds: ['ohid-infant-feeding-2024'],
  },
  {
    id: 'feeding-if-it-doesnt-go-to-plan',
    section: 'feeding-basics',
    title: 'If breastfeeding doesn’t go as planned',
    summary: 'The most common reasons for stopping — and why they say nothing about you.',
    body: [
      '72% of mothers who stopped breastfeeding earlier than planned wished they’d fed for longer. The most common reasons for stopping were: baby not latching or rejecting the breast (45%), feeling they didn’t have enough milk (44%), and painful breasts or nipples (25%).',
      'If this happens to you, it doesn’t reflect anything about you as a mother — these are the most common reasons across the whole country, and support exists specifically because they’re so common.',
    ],
    sourceIds: ['ohid-infant-feeding-2024'],
  },
  {
    id: 'feeding-all-paths-normal',
    section: 'feeding-basics',
    title: 'Combination and formula feeding are mainstream',
    summary: '54% breast milk only, 25% combination, 22% formula only. No failure category.',
    body: [
      'By the time babies left hospital: **54%** of mothers were feeding breast milk only, **25%** a combination of breast and formula, and **22%** formula only.',
      'There’s no "failure" category here — these are simply the three common paths, and each is a normal way to feed a baby.',
      '**Skin-to-skin is for everyone:** 93% of mothers had skin-to-skin contact in the first 24 hours. It’s recommended regardless of how you plan to feed.',
    ],
    sourceIds: ['ohid-infant-feeding-2024'],
    emphasis: 'calm',
  },
  {
    id: 'tongue-tie',
    section: 'feeding-basics',
    title: 'Tongue-tie — common and fixable',
    summary: 'Around 1 in 6 babies. Ask about it specifically if feeding hurts.',
    body: [
      'Around **1 in 6 babies (16%)** are diagnosed with tongue-tie, and it causes feeding problems for about 3 in 4 of those. Most who need a division get one — commonly through an NHS tongue-tie clinic — and most parents who get it done say it helped.',
      'If feeding is painful or your baby seems to struggle latching, **ask specifically about tongue-tie**. It’s not rare, and it’s genuinely treatable.',
    ],
    sourceIds: ['ohid-infant-feeding-2024'],
  },
  {
    id: 'feeding-vitamins-solids',
    section: 'feeding-basics',
    title: 'Vitamin D, solids and allergenic foods',
    summary: 'Breastfed babies need vitamin D from birth. Solids from around 6 months.',
    body: [
      '**Vitamin D:** if you’re breastfeeding, your baby needs a daily vitamin D supplement (8.5–10mcg) from birth — whether or not you’re taking one yourself. From 6 months, most breastfed babies also need vitamins A and C. Formula-fed babies having more than 500ml a day don’t need these, as formula is already fortified.',
      '**Solids from around 6 months**, alongside continued breast or formula milk — not before, and not much later. The biological reason: around 6 months a baby’s energy and nutrient needs start to exceed what breast milk alone can provide.',
      '**Allergenic foods** (egg, peanuts, sesame) should be introduced one at a time, in small amounts, from around 6 months as part of a varied diet. Avoiding them isn’t current advice unless a health professional tells you otherwise. No need to avoid peanuts in pregnancy or while breastfeeding either, unless you’re allergic yourself.',
    ],
    sourceIds: ['ohid-infant-feeding-2024', 'who-infant-feeding'],
  },
  {
    id: 'feeding-benefits-calibrated',
    section: 'feeding-basics',
    title: 'What the evidence actually says about benefits',
    summary: 'Population-level associations — not guarantees for any individual baby.',
    body: [
      'Breastfeeding is linked to a lower chance of infections like diarrhoea and pneumonia in babies, and some evidence links it to lower rates of later childhood overweight.',
      'These are **population-level associations, not guarantees for any individual baby**. However you feed, you’re giving your baby what they need.',
      'Keeping you and your baby together after birth (rather than baby going to a nursery), and feeding as often as your baby wants rather than on a schedule, are both part of the "Baby Friendly" standard UK hospitals are assessed against.',
    ],
    sourceIds: ['who-infant-feeding'],
  },
  {
    id: 'feeding-rights',
    section: 'feeding-basics',
    title: 'Breastfeeding in public is legally protected',
    summary: 'Equality Act 2010. Only about half of mothers know this.',
    body: [
      'The **Equality Act 2010** makes it unlawful to treat you unfavourably for breastfeeding in public — this applies to cafes, shops, and any service open to the public. Only about half of mothers are aware this legal protection exists, so it’s worth knowing it’s there.',
      '**Returning to work:** most mothers found returning didn’t change how they fed their baby (62–71%). If you’re breastfeeding and returning to work, you’re entitled to ask about facilities to express and store milk — raise it with your employer in advance rather than assuming nothing’s available. Your employer must provide somewhere to rest; a private space can be requested, and it should never be a toilet.',
    ],
    sourceIds: ['ohid-infant-feeding-2024', 'nhs-breastfeeding'],
  },

  // ── Breastfeeding detail ───────────────────────────────────────────
  {
    id: 'expressing',
    section: 'breastfeeding',
    title: 'Expressing milk',
    summary: 'By hand or pump, and how long milk keeps.',
    body: [
      '**By hand:** cup your breast in a C-shape 2–3cm back from the nipple, press and release rhythmically, rotating position as flow slows. No equipment needed beyond a sterile container.',
      '**By pump:** massage first to help let-down; start on the lowest setting; switch breasts as flow slows, then switch back. One breast often produces more than the other — normal.',
      '**Storage:** back of the fridge (not the door) up to 8 days at 4°C or colder · ice compartment up to 2 weeks · freezer up to 6 months at −18°C or colder. Label and date everything, and store in small quantities.',
      '**Defrosting:** best thawed in the fridge. If needed urgently, use warm water — **never a microwave**, which creates hot spots that can burn your baby’s mouth. Use immediately once defrosted; never refreeze. Warm with warm water only, use within an hour, and discard leftovers.',
      '**If your baby is premature or unwell:** aim to express 8–12 times in 24 hours including once overnight. Even a few drops early on are valuable.',
    ],
    sourceIds: ['nhs-breastfeeding'],
  },
  {
    id: 'feeding-well',
    section: 'breastfeeding',
    title: 'How to tell your baby is feeding well',
    summary: 'Rounded cheeks, audible swallowing, 6 wet nappies from day 5.',
    body: [
      'Rounded cheeks during sucking (not hollow), audible swallowing, baby coming off the breast on their own when finished, and breasts feeling softer afterwards.',
      'At least **6 wet nappies a day from day 5** onward, and steady weight gain after the first 2 weeks — some initial weight loss is normal.',
      '**Hunger cues** (feed before crying, which is a late sign): restlessness, turning head and opening mouth (rooting), sucking on fists or fingers.',
    ],
    sourceIds: ['nhs-breastfeeding'],
  },
  {
    id: 'breastfeeding-problems',
    section: 'breastfeeding',
    title: 'Common problems and what actually helps',
    summary: 'Sore nipples, mastitis, thrush, colic, reflux — keep feeding through most of them.',
    body: [
      '**Sore nipples** — usually from latch, not something to just endure. Get help early; let nipples air-dry after feeds; avoid soap; cotton non-underwired bras. Avoid nipple shields, as they don’t fix the underlying latch issue.',
      '**Mastitis** — swollen, hot, painful breast area, possibly with flu-like symptoms. **Keep feeding through it** — stopping makes the blockage worse, and it won’t harm your baby even with infection present. Warm compress before feeding, cold after, avoid tight bras. See a GP if not improving within 12–24 hours.',
      '**Thrush** — burning nipple pain, especially after feeds. Needs GP treatment (antifungal cream or tablets) — carry on breastfeeding through it.',
      '**Colic** — inconsolable crying, 3+ hours a day, 3+ days a week. No cure, but burping during and after feeds, sitting baby upright to feed, and checking latch can help. No dietary link is proven.',
      '**Reflux** — bringing up milk during or after feeds, or "silent" reflux with no visible spit-up. Hold baby upright during and after feeding; **always lay them flat on their back to sleep regardless** — never elevate the cot. See your GP if baby’s refusing feeds or not gaining weight.',
      '**Constipation** — fewer than 3 poos a week, hard pellet-like stools. Leg-cycling motion and gentle tummy massage help. A breastfed baby not pooing in 24–48 hours needs checking — it could mean not enough milk.',
    ],
    sourceIds: ['nhs-breastfeeding'],
  },
  {
    id: 'breastfeeding-diet-meds',
    section: 'breastfeeding',
    title: 'Diet, medication and contraception while breastfeeding',
    summary: 'No special diet. Most medicines are fine. Never bed-share after drinking.',
    body: [
      '**Diet:** no special diet needed — varied and balanced is the guidance. Caffeine under 300mg/day (roughly 3 mugs of instant coffee). Fish: 2 portions a week, one oily; limit shark, swordfish and marlin to 1 portion a week. Peanuts are fine unless you’re allergic yourself.',
      '**Alcohol:** the safest approach is to avoid alcohol completely while breastfeeding. If you do drink occasionally, wait at least 2–3 hours per drink before feeding. **Never bed-share or fall asleep with your baby after any alcohol** — this is strongly linked to SIDS risk regardless of amount, and is a firm safety point rather than a judgment call. Regular or heavy drinking can reduce your milk supply and affect your baby’s sleep, growth and development.',
      '**Medication:** most medicines are compatible with breastfeeding — most antibiotics, paracetamol, asthma inhalers, and routine vaccinations (MMR, flu, whooping cough, COVID-19) are all fine. Check with a GP or pharmacist before ibuprofen or anything new, and never stop a prescribed medicine without checking first.',
      '**Contraception:** condoms any time · progestogen-only methods (pill, implant, injection) immediately after birth · combined pill from 6 weeks if breastfeeding · IUD timing discussed with your midwife.',
      '**Vitamin D:** breastfeeding mothers need 10mcg daily.',
    ],
    sourceIds: ['nhs-breastfeeding', 'rcm-infant-feeding', 'nhs-new-parents'],
  },
  {
    id: 'breastfeeding-special',
    section: 'breastfeeding',
    title: 'Special circumstances',
    summary: 'Implants, drugs, COVID-19 — and where to get help.',
    body: [
      '**Breast implants:** breastfeeding is usually possible; risk depends on incision location (around the areola carries more risk to milk ducts). Mention implants to your GP or health visitor so your baby’s weight can be monitored.',
      '**Illegal drugs:** genuinely dangerous while breastfeeding — talk to your midwife or GP without fear of judgment, or contact FRANK on 0300 123 6600.',
      '**COVID-19:** no evidence it passes through breast milk; benefits of continuing generally outweigh risks. Wash hands and avoid coughing on your baby while feeding. The vaccine is safe while breastfeeding.',
      '**Support:** National Breastfeeding Helpline 0300 100 0212 (24/7) · Breastfeeding Network Bengali/Sylheti line 0300 456 2421 · Association of Breastfeeding Mothers 0300 330 5453 · La Leche League 0345 120 2918 · NCT 0300 330 0700.',
    ],
    sourceIds: ['nhs-breastfeeding'],
  },

  // ── Bottle feeding detail ──────────────────────────────────────────
  {
    id: 'bottle-basics',
    section: 'bottle-feeding',
    title: 'Bottle feeding — the basics',
    summary: 'How to hold, pace and wind. Never prop a bottle.',
    body: [
      'You’ll need several bottles, teats, a bottle brush and sterilising equipment. No evidence any particular brand is better — simple, easy-to-wash ones are fine. Always start with **first infant formula**; it’s suitable for the whole first year.',
      'Hold your baby semi-upright, close to you, supporting their head. Look at them and talk to them — bottle feeding is just as much a bonding opportunity. Brush the teat against their lips and let them draw it in.',
      'Keep the bottle roughly horizontal (just slightly tipped) so milk flows steadily without much air. If the teat flattens, gently break the seal at the corner of their mouth; if it blocks, swap in a fresh sterile one.',
      '**Never prop a bottle or leave your baby alone with it** — even briefly, even in bed. Choking risk.',
      'Follow your baby’s lead on amount — they don’t need to finish the bottle. Throw away unused milk after a feed.',
    ],
    sourceIds: ['nhs-bottle-feeding'],
  },
  {
    id: 'sterilising',
    section: 'bottle-feeding',
    title: 'Sterilising',
    summary: 'Needed until 12 months. Dishwashers clean but don’t sterilise.',
    body: [
      'Needed until your baby is 12 months old. Wash equipment in hot soapy water first with a dedicated bottle brush — never use salt to clean teats.',
      '**Cold-water solution:** at least 30 minutes, change solution every 24 hours, no trapped air bubbles. **Steam (electric or microwave):** follow manufacturer instructions. **Boiling:** at least 10 minutes fully submerged — check teats regularly, as they wear faster this way.',
      '**Dishwashers clean but don’t sterilise** — using one isn’t a substitute.',
      'Leave items in the steriliser until needed where possible. If removing early, attach teats and lids immediately and assemble on a clean surface with washed hands.',
    ],
    sourceIds: ['nhs-sterilising'],
  },
  {
    id: 'making-formula',
    section: 'bottle-feeding',
    title: 'Making up a feed — step by step',
    summary: 'Water must still be at 70°C+. Never add extra powder or water.',
    body: [
      '1. Boil at least 1 litre of fresh tap water (never pre-boiled water).',
      '2. Let it cool **no more than 30 minutes** — it needs to stay at 70°C or above to kill bacteria.',
      '3. Clean your surface and wash your hands.',
      '4. Water goes in the bottle **first**, while still hot — check the level carefully.',
      '5. Add powder using only the scoop that came with that formula, levelled off, not packed.',
      '6. Secure the teat and ring tightly, shake to dissolve.',
      '7. Cool under cold running water (lid on) before testing on your wrist — should feel warm or cool, never hot.',
      '8. Discard any leftover made-up formula after the feed.',
      '**Never** add extra powder (risks constipation and dehydration) or extra water (under-nourishes). Never add sugar or cereal. **Never microwave** — uneven heating can burn your baby’s mouth.',
      '**Formula machines** must deliver water at 70°C+ — check with a food thermometer if unsure. **Bottled water** isn’t normally recommended (not sterile, may have too much sodium or sulphate) — emergencies only.',
    ],
    sourceIds: ['nhs-making-formula'],
    emphasis: 'warn',
  },
  {
    id: 'formula-types',
    section: 'bottle-feeding',
    title: 'Types of formula — what’s actually different',
    summary: 'Most babies only ever need first infant formula.',
    body: [
      '**First infant formula:** whey-based, easiest to digest, the only formula most babies need for their whole first year. No evidence switching brands does any good or harm.',
      '**"Hungrier baby" formula:** casein-based, harder to digest — **no evidence it helps babies settle or sleep better.**',
      '**Goats’ milk formula:** nutritionally equivalent, but not suitable for cows’ milk allergy — the proteins are too similar.',
      '**Comfort formula:** partially broken-down protein, no proven benefit for colic or constipation; not suitable for diagnosed allergy.',
      '**Anti-reflux, lactose-free, hypoallergenic and soya formula:** medical supervision or GP prescription only. Don’t self-select these off the shelf.',
      '**Follow-on formula:** not before 6 months, and even then no proven benefit over continuing first formula to age 1. Labels look similar — read carefully.',
      '**Never give under 12 months:** condensed, evaporated or dried milk · goats’ or sheep’s milk as a drink · soya, rice, oat or almond "milks" · cows’ milk as a drink. All are fine in cooking.',
    ],
    sourceIds: ['nhs-formula-types'],
  },
  {
    id: 'bottle-questions',
    section: 'bottle-feeding',
    title: 'Common questions, and feeding away from home',
    summary: 'Posseting, constipation, and how to do it safely out of the house.',
    body: [
      '**Won’t settle after feeds?** Likely swallowed air — hold upright against your shoulder and rub their back gently.',
      '**Sick after feeds (posseting)?** Very common. Check the teat hole isn’t too big, and never force extra milk. Get checked if it’s violent, frequent, or your baby seems in pain.',
      '**Constipation?** Always use the exact amount of powder stated. No poo for 2–3 days under 8 weeks old needs checking, especially with slow weight gain.',
      '**Away from home:** take measured powder in a small clean container, a flask of freshly boiled water, and an empty sterilised bottle. Make up fresh only when needed. If you can’t follow that, use ready-to-feed liquid formula instead.',
      '**Is my baby getting enough?** Around 6 wet nappies a day from a few days old, and at least one poo daily moving from meconium to pale yellow or brown within the first week.',
    ],
    sourceIds: ['nhs-bottle-feeding', 'nhs-making-formula'],
  },
  {
    id: 'combining-feeding',
    section: 'bottle-feeding',
    title: 'Combining breast and bottle',
    summary: 'Both directions — and how to protect supply if you want to.',
    body: [
      'Introducing formula alongside breastfeeding will reduce your milk supply somewhat, and there’s some evidence babies can find switching between different sucking actions tricky. Neither is a reason not to do it if it’s what works for you.',
      '**Introducing formula:** do it gradually to avoid engorgement or mastitis. Start a few weeks before returning to work if that’s the plan. If your baby is 6+ months and cup-drinking, you may not need a bottle at all.',
      '**First bottle tips:** offer when your baby is relaxed, not ravenous; it can help if someone else gives it, away from the smell of your milk; try a different feeding position than usual.',
      '**Going the other way — more breastfeeding, fewer bottles:** skin-to-skin contact, expressing regularly (ideally around 8 times a day including once overnight), bottle-feeding while skin-to-skin, feeding often even if briefly at first, and reducing bottles gradually as supply increases. A lactation aid — a fine tube taped near the nipple — is a real option a midwife or health visitor can show you.',
    ],
    sourceIds: ['nhs-combine-feeding'],
  },
];
