import type { Guide } from '../schema';

export const postnatalGuides: Guide[] = [
  {
    id: 'first-days',
    section: 'first-days',
    title: 'The first days',
    summary: 'Skin-to-skin, newborn checks, and who sees you when.',
    body: [
      '**Your baby:** skin-to-skin straight after birth helps bonding and breastfeeding. Babies normally lose some weight in the first few days — steady gain after that is the sign things are going well. Most regain their birthweight within 3 weeks.',
      '**Checks offered:** newborn physical examination within 72 hours; blood spot (heel prick) test around day 5; hearing screening before 4 weeks. Midwives also check for jaundice, cord or eye infection, and thrush.',
      '**You:** staff will check your temperature, pulse, blood pressure, breathing, bleeding, and whether you can wee and poo. They’ll feel your tummy to check your womb is shrinking — tummy pain when it does, especially while breastfeeding, is normal.',
      '**Who sees you when:** midwives visit until around day 10, then a health visitor takes over at 10–14 days.',
    ],
    sourceIds: ['nhs-early-days'],
  },
  {
    id: 'postnatal-bleeding',
    section: 'first-days',
    title: 'Postnatal bleeding — and when it’s not normal',
    summary: 'Lochia lasts weeks. Sudden heavy bleeding is a 999 call.',
    body: [
      'Bleeding (lochia) lasts a few weeks, usually stopping by 6–8 weeks. It changes from red, to pink or brown, to whitish.',
      '**Speak to your GP, midwife or health visitor if:** temperature over 38°C · the bleeding smells unusual for you · tummy pain getting worse · bleeding gets heavier or doesn’t reduce · clots · worsening pain between vagina and anus. These can signal infection.',
      '**Call 999 if:** bleeding is sudden and very heavy, or you feel faint, dizzy, or have a pounding heart. This could be a postpartum haemorrhage.',
    ],
    sourceIds: ['nhs-early-days'],
    emphasis: 'warn',
  },
  {
    id: 'postnatal-check',
    section: 'first-days',
    title: 'Your 6-week postnatal check',
    summary: 'What it covers — and what to raise even if it feels awkward.',
    body: [
      'You should have a postnatal check 6–8 weeks after birth, offered by your GP surgery. You can also request one yourself, especially if you have concerns. Worth making a list of questions beforehand.',
      'It usually covers: how you’re feeling (mental health and wellbeing), whether you still have discharge or have had a period, blood pressure if you had problems in pregnancy, healing of any stitches from an episiotomy or caesarean, contraception, and vitamin D if you’re breastfeeding.',
      'Your baby has their own 6–8 week check around the same time — the two can be done together or separately, whichever you prefer.',
      '**Things to tell your doctor, even if they feel awkward:** you’re feeling sad or anxious (looking after a baby can feel overwhelming — it isn’t a sign you’re a bad mother, and you don’t have to put on a brave face) · you’re having trouble controlling wind, wee or poo · sex is painful · you’re not sure you’ve had all recommended adult vaccines.',
    ],
    sourceIds: ['nhs-postnatal-check'],
  },
  {
    id: 'newborn-weeks',
    section: 'first-days',
    title: 'The early weeks with a newborn',
    summary: 'Sleep in 2–3 hour stretches, feed on demand, and reducing SIDS risk.',
    body: [
      'Newborns typically sleep only 2–3 hours at a time, day or night — they aren’t tuned into day and night yet, and their stomachs are tiny so they need to feed little and often. This changes as they grow.',
      'You don’t need to bathe your baby in the first few days — washing face, neck, hands and bottom ("topping and tailing") is enough. Feed as often as your baby wants, and let them decide when they’ve had enough.',
      '**Reducing SIDS risk:** put your baby on their back to sleep, in a cot in the same room as you, for the first 6 months. Don’t smoke during pregnancy or breastfeeding, and don’t let anyone smoke in the same room as your baby. SIDS is rare — don’t let worrying about it stop you enjoying your baby’s first months.',
      '**Trust your instincts.** It can be hard to tell when a baby is seriously ill. You know your baby better than anyone — if their appearance or behaviour worries you, act on it.',
    ],
    sourceIds: ['nhs-new-parents'],
  },
  {
    id: 'body-after-birth',
    section: 'recovery',
    title: 'Your body after birth',
    summary: 'Separated stomach muscles, pelvic floor, and back pain.',
    body: [
      '**Separated stomach muscles (diastasis recti):** common — usually about two finger-widths. It normally closes by 8 weeks. If the gap is still obvious at 8 weeks, contact your GP; you may need physio. Avoid sit-ups, planks, heavy lifting and straining early on.',
      '**Pelvic floor exercises:** squeeze and draw in as if holding wind, then squeeze around your vagina and bladder. Do long holds (up to 10 seconds) and short quick squeezes. Build to 10 reps of each, 3 times a day. Keep breathing; don’t pull your stomach in.',
      '**Back pain:** sit with your back supported when feeding, feet reaching the floor. Kneel or squat rather than bending. Change nappies on a raised surface. Bend your knees when lifting.',
    ],
    sourceIds: ['nhs-post-pregnancy-body'],
  },
  {
    id: 'lasting-problems',
    section: 'recovery',
    title: 'Problems that last — the honest one',
    summary: 'Far more common than most people are told, and largely underreported.',
    body: [
      'Some problems last well beyond the 6-week check, and they’re far more common than most people are told. WHO research published in 2023 found that among women after childbirth: around **35% experience pain during sex**, 32% low back pain, 19% anal incontinence, 8–31% urinary incontinence, 11–17% depression, 9–24% anxiety, and 11% perineal pain.',
      'These are described in the research as largely **underrecognised and underreported** — partly because they often appear after postnatal services have stopped.',
      'If something is still a problem, you are not being difficult by raising it. Ask your GP or health visitor at any point; they can refer you to a specialist.',
    ],
    sourceIds: ['who-lancet-perinatal-2023'],
    emphasis: 'calm',
  },
  {
    id: 'postnatal-depression',
    section: 'postnatal-mind',
    title: 'Postnatal depression',
    summary: 'More than 1 in 10 women, within a year. Treatable, usually within 3–6 months.',
    body: [
      '**Baby blues vs PND:** baby blues usually starts 2–3 days after birth and passes within about 2 weeks. Postnatal depression is sadness, hopelessness, guilt or self-blame lasting most of the time for weeks or months. It can start in pregnancy, soon after birth, or any time up to a year after.',
      '**More than 1 in 10 women** get PND within a year of giving birth. Fathers and partners can get it too.',
      '**Symptoms:** low mood that won’t lift · not enjoying things · trouble sleeping even when exhausted · difficulty concentrating · anxiety · avoiding people · guilt and self-blame · difficulty bonding with your baby · thoughts of suicide or of harming yourself or your baby.',
      'It’s a mental health condition — not weakness, and not something to snap out of. It usually gets better with treatment, typically within 3 to 6 months.',
      '**A fear worth naming:** many people worry their baby will be taken away if they admit how they’re feeling. This is very rare. Your care team’s job is to support you to care for your baby.',
      '**Getting help:** speak to your GP, midwife or health visitor. If you’re 18 or over (16 in some areas), you can self-refer to NHS talking therapies without a GP referral. If you’re breastfeeding, say so — it affects what they’d suggest.',
      '**Support:** Samaritans 116 123 · PANDAS 0808 1961 776 · APNI 0207 386 0868 · Mind 0300 123 3393.',
    ],
    sourceIds: ['nhs-postnatal-depression', 'tommys-pnd'],
  },
  {
    id: 'sex-contraception-after',
    section: 'recovery',
    title: 'Sex, contraception and fertility after birth',
    summary: 'You can get pregnant from 21 days after birth — before periods return.',
    body: [
      'You can get pregnant **from 21 days after birth** — before your periods return, and even while breastfeeding. Use contraception from day 21 if you don’t want to conceive again.',
      '**Available straight away, including while breastfeeding:** implant, injection, progestogen-only pill, condoms, IUD or IUS (if fitted within 48 hours — otherwise wait 4 weeks).',
      '**From 3 weeks** (if not breastfeeding and no clot risk factors): combined pill, ring, patch. If breastfeeding, usually from 6 weeks.',
      '**From 6 weeks:** diaphragm or cap — get refitted, as your size may have changed.',
      '**Sex:** there are no rules about when. If it hurts, say so — hormonal changes can make you drier, and lubricant helps. If it’s still painful at your postnatal check, tell your GP.',
    ],
    sourceIds: ['nhs-sex-contraception-after'],
  },
  {
    id: 'getting-active-again',
    section: 'recovery',
    title: 'Getting active again',
    summary: 'Gentle straight away; wait for your 6–8 week check before high impact.',
    body: [
      '**Straightforward birth:** gentle exercise as soon as you feel up to it — walking, stretches, pelvic floor. Wait until after your 6–8 week check before high-impact exercise like running or aerobics.',
      '**Caesarean or complicated birth:** longer recovery. Talk to your midwife, health visitor or GP first.',
      'Worth knowing: your ligaments and joints stay more flexible for months after birth, so there’s a higher injury risk from stretching or twisting too far. Get remeasured for a sports bra — and possibly shoes, as feet can change shape.',
      '**Swimming:** wait until 7 days after your postnatal bleeding has stopped.',
      'Regular activity may help prevent postnatal depression, alongside its physical benefits.',
    ],
    sourceIds: ['nhs-fit-with-baby'],
  },
  {
    id: 'getting-support',
    section: 'postnatal-support',
    title: 'Getting support',
    summary: 'Health visitors, Family Hubs, and helplines that actually pick up.',
    body: [
      'Register your baby with a GP as early as you can.',
      'Your **health visitor** — a nurse or midwife with extra training — usually does a new baby review around 10 days, then ongoing checks recorded in your baby’s red book. They’re a good first port of call for mental health worries and for finding local groups.',
      '**Family Hubs** (in some areas) bring parenting classes, health visitors, feeding support and postnatal mental health support into one place.',
      '**If you’re parenting alone:** Gingerbread offers advice on benefits, housing and child maintenance, and can connect you with other single parents.',
      '**Other helplines:** Coram Family Lives 0808 800 2222 · Contact (disabled children) 0808 808 3555 · Parent Talk (WhatsApp) 0770 017 4470.',
    ],
    sourceIds: ['nhs-parent-support', 'nhs-single-parents'],
  },
];
